[package]
distribution = "2201.2.1"
org= "ballerinax"
name= "microsoft.teams"
version= "2.3.0"
authors = ["Ballerina"]
keywords = ["Communication/Team Chat", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.teams"
license = ["Apache-2.0"]

[build-options]
observability-included=true

